FLUTTER_CMD=flutter
DART_CMD=dart

run:
	$(FLUTTER_CMD) run

build:
	$(FLUTTER_CMD) build

test:
	$(FLUTTER_CMD) test

clean:
	$(FLUTTER_CMD) clean 

install:
	$(FLUTTER_CMD) pub get

build_runner:
	$(DART_CMD) run build_runner build